version: '3.8'

services:
  backend:
    container_name: api
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
      - "5050:5050"
      - "7070:7070"
    volumes:
      - ./:/app
    environment:
      - PORT=5000
      - DB_HOST=mysql-data
      - DB_PORT=3306
      - DB_PASSWORD=abc12345
      - DB_NAME=qairline-dtb
    depends_on:
      - mysql
      - redis
    restart: always
    networks:
      - backend_api

  redis:
    image: redis:7-alpine
    container_name: api_redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - backend_api

  mysql:
    image: mysql:8.0.31
    container_name: api_mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc12345
      MYSQL_DATABASE: qairline-dtb
    ports:
      - "3306:3306"
    volumes:
      # - ./mysql-data:/var/lib/mysql
      - ./migration/qairline.sql:/docker-entrypoint-initdb.d/qairline.sql
    networks:
      - backend_api

networks:
  backend_api:
    driver: bridge