version: "3.8"

services:
  web:
    container_name: api
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
      - "5555:5555"
      - "7070:7070"
    environment:
      - PORT=5000
    depends_on:
      - mysql
      - redis
    restart: always
    volumes:
      - ./:/app
    networks:
      - web_api
      
  mysql:
    image: mysql:8.0.31
    container_name: api_mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: abc12345
      MYSQL_DATABASE: qairline-dtb
    volumes:
      # - ./mysql-data:/var/lib/mysql
      - ./migration/qairline.sql:/docker-entrypoint-initdb.d/qairline.sql
    networks:
      - web_api


networks:
  web_api:
    driver: bridge
