version: '3.8'

services:
  backend:
    container_name: api
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
      - "5050:5050"
      - "7070:7070"
    volumes:
      - ./backend:/app
    environment:
      - PORT=5000
      - DB_HOST=mysql-data
      - DB_PORT=3306
      - DB_PASSWORD=abc12345
      - DB_NAME=qairline-dtb
    depends_on:
      - mysql
    restart: always
    networks:
      - backend_api

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: abc12345
      MYSQL_DATABASE: qairline-dtb
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - backend_api

networks:
  backend_api:
    driver: bridge